# Generated by Django 5.0 on 2023-12-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0002_category_categoryname"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="maxXP",
            field=models.IntegerField(default=50),
        ),
    ]
