# Generated by Django 5.0 on 2023-12-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0004_remove_schedule_taskid_schedule_taskid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completedFlag",
        ),
        migrations.CreateModel(
            name="completed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completedFlag", models.BooleanField(default=False)),
                (
                    "taskID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.task"
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("userID", "taskID")},
            },
        ),
    ]
