# Generated by Django 5.0 on 2023-12-27 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0007_completed_datecompleted_completed_streak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tempDate",
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
