# Generated by Django 5.0 on 2023-12-29 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0008_userprofile_tempdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="tempDate",
        ),
    ]
